name: LovSonar Weekly Scan

on:
  schedule:
    # Kjører kl. 08:00 hver mandag (UTC)
    - cron: '0 8 * * 1'
  workflow_dispatch: # Lar deg starte skanningen manuelt med en knapp

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v3

      - name: Sett opp Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installer avhengigheter
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Kjør LovSonar
        env:
          # Her kobles GitHub Secrets til koden din
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
        run: python lovsonar.py
